<?php

namespace App\Models;

use App\Http\Requests\AddPostRequest;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Support\Facades\Auth;

class Posts  extends Authenticatable
{


    protected $fillable = [
        'header',
        'info',
        'signature',
        'user_id'
    ];



    public static  function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        // it will automatically add authenticate user to user_id column of selected model
        static::creating(function ($model){
            $model->user_id = Auth::user()->id;
        });
    }

}
